version: '3'

services:
  app:
    container_name: app
    depends_on:
      - mongo
    build:
      context: ./
      dockerfile: Dockerfile
    command: yarn run dev
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/node-feature
      - /usr/src/node-feature/node_modules

  mongo:
    container_name: mongo
    image: mongo:3.6
    command: mongod
